name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: printing greeting
        run: echo "Hello world"
      - name: printing goodBye
        run: echo "Done -Bye"
    
